# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TrillDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TrillDemo 
  pod 'Just',:inhibit_warnings => true
  pod 'Kingfisher',:inhibit_warnings => true
  pod 'MarqueeLabel',:inhibit_warnings => true
  pod 'NVActivityIndicatorView',:inhibit_warnings => true
  pod 'ChainableAnimations',:inhibit_warnings => true
  pod 'SnapKit',:inhibit_warnings => true

end
